# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit
from Services.login_logic import login
from Services.reset_logic import reset
from Modules.managementWindowModule import ManagementWindow

class Ui_loginWindow(object):
    def setupUi(self, loginWindow):

        loginWindow.setObjectName("loginWindow")
        loginWindow.resize(1080, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("symvolika-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        loginWindow.setWindowIcon(icon)
        loginWindow.setStyleSheet("background: #5472DE;\n"
"background-image: url(:/newPrefix/649eb8ca76c20 (1).png);")
        self.centralwidget = QtWidgets.QWidget(loginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(440, 80, 121, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("background: transparent;")
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")

        self.label1 = QtWidgets.QPushButton(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(500, 500, 80, 40))
        self.label1.setObjectName("label")
        self.label1.setStyleSheet("background: transparent;")

        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(560, 80, 111, 111))
        self.widget_2.setStyleSheet("image: url(:/newPrefix/symvolika-1.png);\n"
"background: transparent;")
        self.widget_2.setObjectName("widget_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(340, 210, 391, 51))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(340, 290, 391, 51))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setEchoMode(QLineEdit.Password)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 390, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(139, 179, 255);")
        self.pushButton.setObjectName("pushButton")
        loginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(loginWindow)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)
        self.add_functions()


    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "Вхід в систему"))
        self.label_6.setText(_translate("loginWindow", "Логін"))
        self.lineEdit.setPlaceholderText(_translate("loginWindow", "Ваш логін"))
        self.lineEdit_2.setPlaceholderText(_translate("loginWindow", "Ваш пароль"))
        self.pushButton.setText(_translate("loginWindow", "Увійти"))
        self.label1.setText(_translate("Forgotpass", "Забув пароль"))

    def add_functions(self):
        self.pushButton.clicked.connect(self.loginProcess)
        self.label1.clicked.connect(self.resetProccess)

    def resetProccess(self):
        reset(self.lineEdit)

    def loginProcess(self):
        username = self.lineEdit.text()
        password = self.lineEdit_2.text()

        if login(username, password):
            QtWidgets.QMessageBox.information(None, "Успіх", "Логін пройшов успішно!")
            self.management_window = ManagementWindow(username)
            self.management_window.show()
        else:
            QtWidgets.QMessageBox.critical(None, "Помилка", "Перевірте правильність даних.")



