# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orderWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pymysql
from PyQt5 import QtCore, QtGui, QtWidgets
from Services.data_operations import save_data

class Ui_orderWindow(object):
    def __init__(self):
        self.connection = None  # Ініціалізуємо connection

    def set_connection(self, connection):
        self.connection = connection

    def setupUi(self, orderWindow):
        orderWindow.setObjectName("orderWindow")
        orderWindow.resize(1080, 600)
        orderWindow.setStyleSheet("background: #5472DE;\n"
"background-image: url(:/newPrefix/649eb8ca76c20 (1).png);")
        self.centralwidget = QtWidgets.QWidget(orderWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(320, 10, 421, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("background: transparent;")
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(370, 120, 320, 50))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 190, 81, 16))
        self.label.setStyleSheet("background: transparent;")
        self.label.setObjectName("label")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(370, 210, 320, 50))
        self.comboBox_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setGeometry(QtCore.QRect(370, 300, 320, 50))
        self.comboBox_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_7.setObjectName("comboBox_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 280, 101, 16))
        self.label_2.setStyleSheet("background: transparent;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 370, 141, 16))
        self.label_3.setStyleSheet("background: transparent;")
        self.label_3.setObjectName("label_3")
        self.comboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_8.setGeometry(QtCore.QRect(370, 390, 320, 50))
        self.comboBox_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_8.setObjectName("comboBox_8")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(380, 480, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_5.setMouseTracking(False)
        self.pushButton_5.setStyleSheet("background: #8BB3FF;\n"
"font-family: Arial;\n"
"cursor: pointer;")
        self.pushButton_5.setObjectName("pushButton_5")
        orderWindow.setCentralWidget(self.centralwidget)

        self.pushButton_5.clicked.connect(self.save_data)

        self.retranslateUi(orderWindow)
        QtCore.QMetaObject.connectSlotsByName(orderWindow)

    def load_combobox_data(self, connection):
        try:
            with connection.cursor() as cursor:
                # Query to fetch specialty ID and name
                cursor.execute("SELECT id, name FROM specialties")
                specialties = cursor.fetchall()

                # Clear any existing items in the combo box
                self.comboBox_6.clear()

                # Populate comboBox_6 with the name but store the ID
                for specialty in specialties:
                    self.comboBox_6.addItem(specialty[1], specialty[0])

                # Populate comboBox_7 (Privileges) with "Так" and "Ні"
                self.comboBox_7.clear()
                self.comboBox_7.addItems(["Ні", "Так"])

                # Populate comboBox_8 (Enrollment type) with "Так" and "Ні"
                self.comboBox_8.clear()
                self.comboBox_8.addItems(["Ні", "Так"])

        except pymysql.MySQLError as e:
            print(f"Error fetching data: {e}")

    def save_data(self):
        if self.connection is None:
            print("З'єднання з базою даних не встановлене.")
            return

        name = self.lineEdit_4.text()
        specialty_id = self.comboBox_6.currentData()
        is_privileged = self.comboBox_7.currentIndex()
        transfer = self.comboBox_8.currentIndex()

        if not name or specialty_id is None:
            QtWidgets.QMessageBox.warning(None, "Помилка", "Всі поля мають бути заповнені.")
            return

        save_data(self.connection, name, specialty_id, is_privileged, transfer)

    def retranslateUi(self, orderWindow):
        _translate = QtCore.QCoreApplication.translate
        orderWindow.setWindowTitle(_translate("orderWindow", "Заява на вступ"))
        self.label_6.setText(_translate("orderWindow", "Створення заяви"))
        self.lineEdit_4.setPlaceholderText(_translate("orderWindow", "ПІБ"))
        self.label.setText(_translate("orderWindow", "Спеціальність"))
        self.label_2.setText(_translate("orderWindow", "Ви пільговик?"))
        self.label_3.setText(_translate("orderWindow", "Ви переводитесь?"))
        self.pushButton_5.setText(_translate("orderWindow", "Відправити"))
import WindowFiles.img.image_rc