# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'queryWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Services.queryService import Query
from Services.login_logic import DatabaseConnection


class Ui_Query(object):
    def setupUi(self, Management):
        Management.setObjectName("Management")
        Management.resize(1920, 1080)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Downloads/symvolika-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Management.setWindowIcon(icon)
        Management.setStyleSheet("background: #5472DE;\n"
                                 "background-image: url(:/newPrefix/649eb8ca76c20 (1).png);")
        self.centralwidget = QtWidgets.QWidget(Management)
        self.centralwidget.setObjectName("centralwidget")

        # Adjusted label position
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(600, 50, 741, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("background: transparent;")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        # Adjusted combo box label position
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1370, 180, 281, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet("background: transparent;")
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")

        # Line edit above combo box
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(1390, 270, 300, 40))  # New line edit above combo box
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")

        # Adjusted button position and width
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(1390, 460, 300, 60))  # Adjusted button position
        self.pushButton_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_16.setObjectName("pushButton_16")

        # Adjusted table widget position
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(190, 220, 1161, 701))
        self.tableWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setWordWrap(False)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)

        # Adjusted combo box position and width
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(1390, 350, 300, 60))  # Adjusted combo box position
        self.comboBox_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_5.setObjectName("comboBox_5")

        Management.setCentralWidget(self.centralwidget)

        # Database connection and query initialization
        self.connection = DatabaseConnection.get_connection()
        self.query = Query(self.connection)

        # Load query names and connect button
        self.load_query_names()
        self.pushButton_16.clicked.connect(self.execute_selected_query)

        self.retranslateUi(Management)
        QtCore.QMetaObject.connectSlotsByName(Management)

    def load_query_names(self):
        query_names = [
            "Запит 1: Групи з 3-ма екзаменами",
            "Запит 1.2: Групи з більше 3 екзаменів",
            "Запит 1.3: Групи з творчим конкурсом",
            "Запит 2: Групи з різними спеціальностями",
            "Запит 3: Дисципліни для спеціальності",
            "Запит 4: Середній бал по екзаменам для спеціальності",
            "Запит 5: Кількість заявок на факультет",
            "Запит 5.2: Кількість заявок на спеціальність",
            "Запит 5.3: Спеціальності з менше 10 заявками",
            "Запит 6: Абітурієнти на заданий факультет",
            "Запит 6.2: Абітурієнти на задану спеціальність",
            "Запит 6.3: Абітурієнти-пільговики",
            "Запит 7: Абітурієнти на механізм переводу",
            "Запит 7.2: Абітурієнти на механізм переводу з тими ж самими іспитами",
            "Запит 8: Абітурієнти з результатами нижче прохідного балу",
            "Запит 8.2: Абітурієнти провалили 1 предмет",
            "Запит 8.3: Абітурієнти провалили 2 предмета",
            "Запит 8.4: Абітурієнти провалили творчий конкурс",
            "Запит 9: Викладачі які приймають заданий екзамен",
            "Запит 10: Спеціальності з екзаменом 'Математика'"
        ]
        self.comboBox_5.addItems(query_names)

    def execute_selected_query(self):
        selected_index = self.comboBox_5.currentIndex()

        if selected_index == 0:
            self.query.query1(self.tableWidget_2)
        elif selected_index == 1:
            self.query.query12(self.tableWidget_2)
        elif selected_index == 2:
            self.query.query13(self.tableWidget_2)
        elif selected_index == 3:
            self.query.query2(self.tableWidget_2)
        elif selected_index == 4:
            specialty_id = self.lineEdit.text()
            if not specialty_id:
                QtWidgets.QMessageBox.warning(None, "Помилка", "Введіть назву спеціальності.")
                return
            self.query.query3(self.tableWidget_2, specialty_id)
        elif selected_index == 5:
            specialty_id = self.lineEdit.text()
            if not specialty_id:
                QtWidgets.QMessageBox.warning(None, "Помилка", "Введіть назву спеціальності.")
                return
            self.query.query4(self.tableWidget_2, specialty_id)
        elif selected_index == 6:
            self.query.query5(self.tableWidget_2)
        elif selected_index == 7:
            self.query.query52(self.tableWidget_2)
        elif selected_index == 8:
            self.query.query53(self.tableWidget_2)
        elif selected_index == 9:
            faculty_id = self.lineEdit.text()
            if not faculty_id:
                QtWidgets.QMessageBox.warning(None, "Помилка", "Введіть назву факультету.")
                return
            self.query.query6(self.tableWidget_2, faculty_id)
        elif selected_index == 10:
            specialty_id = self.lineEdit.text()
            if not specialty_id:
                QtWidgets.QMessageBox.warning(None, "Помилка", "Введіть назву спеціальності.")
                return
            self.query.query62(self.tableWidget_2, specialty_id)
        elif selected_index == 11:
            self.query.query63(self.tableWidget_2)
        elif selected_index == 12:
            self.query.query7(self.tableWidget_2)
        elif selected_index == 13:
            self.query.query72(self.tableWidget_2)
        elif selected_index == 14:
            self.query.query8(self.tableWidget_2)
        elif selected_index == 15:
            self.query.query82(self.tableWidget_2)
        elif selected_index == 16:
            self.query.query83(self.tableWidget_2)
        elif selected_index == 17:
            self.query.query84(self.tableWidget_2)
        elif selected_index == 18:
            exam_id = self.lineEdit.text()
            if not exam_id:
                QtWidgets.QMessageBox.warning(None, "Помилка", "Введіть номер екзамену.")
                return
            self.query.query9(self.tableWidget_2, exam_id)
        elif selected_index == 19:
            self.query.query10(self.tableWidget_2)

    def retranslateUi(self, Management):
        _translate = QtCore.QCoreApplication.translate
        Management.setWindowTitle(_translate("Management", "Керування БД"))
        self.label_3.setText(_translate("Management", "Виконати запит"))
        self.label_9.setText(_translate("Management", "Виберіть запит"))
        self.pushButton_16.setText(_translate("Management", "Виконати"))
        self.lineEdit.setPlaceholderText(_translate("Management", "Опція для запиту"))
        self.tableWidget_2.setSortingEnabled(True)
import WindowFiles.img.image_rc