# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teacherWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Services.login_logic import DatabaseConnection
from Services.teachersService import Teachers

class Ui_Teachers(object):
    def setupUi(self, Management):
        Management.setObjectName("Management")
        Management.resize(1920, 1080)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Downloads/symvolika-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Management.setWindowIcon(icon)
        Management.setStyleSheet("background: #5472DE;\n"
"background-image: url(:/newPrefix/649eb8ca76c20 (1).png);")
        self.centralwidget = QtWidgets.QWidget(Management)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(620, 50, 741, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("background: transparent;")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_16.setGeometry(QtCore.QRect(1300, 290, 251, 51))
        self.lineEdit_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1280, 190, 281, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet("background: transparent;")
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(100, 220, 271, 51))
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(1300, 350, 251, 51))
        self.pushButton_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(990, 220, 271, 51))
        self.pushButton_18.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_18.setObjectName("pushButton_18")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(100, 290, 1161, 691))
        self.tableWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setWordWrap(False)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(1590, 290, 251, 51))
        self.pushButton_17.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_17.setObjectName("pushButton_17")
        Management.setCentralWidget(self.centralwidget)

        self.connection = DatabaseConnection.get_connection()

        self.teachers = Teachers(self.connection)
        self.teachers.load_data_to_tablewidget(self.tableWidget_2)

        self.lineEdit_6.textChanged.connect(self.search)

        self.pushButton_16.clicked.connect(self.save_data)
        self.pushButton_17.clicked.connect(self.delete_record)
        self.pushButton_18.clicked.connect(self.update_data)

        self.retranslateUi(Management)
        QtCore.QMetaObject.connectSlotsByName(Management)

    def search(self):
        keyword = self.lineEdit_6.text()
        self.teachers.search_data(keyword, self.tableWidget_2)

    def delete_record(self):
        self.teachers.delete_selected_record(self.tableWidget_2)

    def save_data(self):
        if self.connection is None:
            print("З'єднання з базою даних не встановлене.")
            return

        name = self.lineEdit_16.text()

        if not name:
            QtWidgets.QMessageBox.warning(None, "Помилка", "Всі поля мають бути заповнені.")
            return

        self.teachers.save_data(name)
        self.teachers.load_data_to_tablewidget(self.tableWidget_2)

    def update_data(self):
        self.teachers.update_data(self.tableWidget_2)

    def retranslateUi(self, Management):
        _translate = QtCore.QCoreApplication.translate
        Management.setWindowTitle(_translate("Management", "Керування БД"))
        self.label_3.setText(_translate("Management", "Викладачі"))
        self.lineEdit_16.setPlaceholderText(_translate("Management", "Назва"))
        self.label_9.setText(_translate("Management", "Додати викладача"))
        self.lineEdit_6.setPlaceholderText(_translate("Management", "Пошук по ключовому слову"))
        self.pushButton_16.setText(_translate("Management", "Додати"))
        self.pushButton_18.setText(_translate("Management", "Зберегти зміни"))
        self.tableWidget_2.setSortingEnabled(True)
        self.pushButton_17.setText(_translate("Management", "Видалити вибраний запис"))
import WindowFiles.img.image_rc

