# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'usersWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Services.login_logic import DatabaseConnection
from Services.userService import Users

class Ui_usersWindow(object):
    def setupUi(self, resultWindow):
        resultWindow.setObjectName("resultWindow")
        resultWindow.resize(1920, 1090)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Downloads/symvolika-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        resultWindow.setWindowIcon(icon)
        resultWindow.setStyleSheet("background: #5472DE;\n"
"background-image: url(:/newPrefix/649eb8ca76c20 (1).png);")
        self.centralwidget = QtWidgets.QWidget(resultWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(590, 40, 741, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("background: transparent;")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(1070, 510, 251, 51))
        self.pushButton_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_16.setObjectName("pushButton_16")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(1070, 440, 251, 51))
        self.comboBox_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(270, 220, 271, 51))
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_16.setGeometry(QtCore.QRect(1070, 290, 251, 51))
        self.lineEdit_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(760, 220, 251, 51))
        self.pushButton_17.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1050, 190, 281, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet("background: transparent;")
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(270, 290, 741, 691))
        self.tableWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setWordWrap(False)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(1340, 510, 251, 51))
        self.pushButton_18.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_18.setObjectName("pushButton_18")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1070, 420, 91, 16))
        self.label.setObjectName("label")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_17.setGeometry(QtCore.QRect(1070, 360, 251, 51))
        self.lineEdit_17.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(1340, 290, 251, 51))
        self.comboBox_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(1340, 440, 251, 51))
        self.comboBox_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_6.setObjectName("comboBox_6")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(1320, 190, 281, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setStyleSheet("background: transparent;")
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_18.setGeometry(QtCore.QRect(1340, 360, 251, 51))
        self.lineEdit_18.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1340, 420, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1340, 270, 41, 16))
        self.label_4.setObjectName("label_4")
        resultWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(resultWindow)
        QtCore.QMetaObject.connectSlotsByName(resultWindow)

        self.connection = DatabaseConnection.get_connection()

        self.users = Users(self.connection)

        self.users.load_data_to_tablewidget(self.tableWidget_2)
        self.users.load_combobox_data(self.comboBox_5, self.comboBox_4, self.comboBox_6)

        self.lineEdit_6.textChanged.connect(self.search)

        self.pushButton_16.clicked.connect(self.save_data)
        self.pushButton_17.clicked.connect(self.delete_record)
        self.pushButton_18.clicked.connect(self.update_data)

    def search(self):
        keyword = self.lineEdit_6.text()
        self.users.search_data(keyword, self.tableWidget_2)

    def save_data(self):
        if self.connection is None:
            print("З'єднання з базою даних не встановлене.")
            return

        username = self.lineEdit_16.text()
        password = self.lineEdit_17.text()
        access = self.comboBox_4.currentText()

        if not username or password is None:
            QtWidgets.QMessageBox.warning(None, "Помилка", "Всі поля мають бути заповнені.")
            return

        self.users.save_data(username, password, access)
        self.users.load_data_to_tablewidget(self.tableWidget_2)
        self.users.load_combobox_data(self.comboBox_5, self.comboBox_4, self.comboBox_6)

    def delete_record(self):
        self.users.delete_selected_record(self.tableWidget_2)

    def update_data(self):
        username = self.comboBox_5.currentText()
        password = self.lineEdit_18.text()
        access = self.comboBox_6.currentText()
        self.users.update_data(username, password, access)
        self.users.load_data_to_tablewidget(self.tableWidget_2)

    def retranslateUi(self, resultWindow):
        _translate = QtCore.QCoreApplication.translate
        resultWindow.setWindowTitle(_translate("resultWindow", "Керування БД"))
        self.label_3.setText(_translate("resultWindow", "Користувачі"))
        self.pushButton_16.setText(_translate("resultWindow", "Додати"))
        self.lineEdit_6.setPlaceholderText(_translate("resultWindow", "Пошук по ключовому слову"))
        self.lineEdit_16.setPlaceholderText(_translate("resultWindow", "Юзернейм"))
        self.pushButton_17.setText(_translate("resultWindow", "Видалити вибраний запис"))
        self.label_9.setText(_translate("resultWindow", "Додати юзера"))
        self.tableWidget_2.setSortingEnabled(True)
        self.pushButton_18.setText(_translate("resultWindow", "Зберегти зміни"))
        self.label.setText(_translate("resultWindow", "Права доступу"))
        self.lineEdit_17.setPlaceholderText(_translate("resultWindow", "Пароль"))
        self.label_10.setText(_translate("resultWindow", "Редагувати юзера"))
        self.lineEdit_18.setPlaceholderText(_translate("resultWindow", "Новий пароль"))
        self.label_2.setText(_translate("resultWindow", "Права доступу"))
        self.label_4.setText(_translate("resultWindow", "Юзер"))
import WindowFiles.img.image_rc
